import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "../../styles/globals.css";
import { cn } from "../../lib/utils";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import theme from "../../styles/theme";
import { ThemeProvider } from "@mui/material/styles";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-gray-200 font-sans antialiased",
          fontSans.variable,
        )}
      >
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
